apiVersion: apps/v1
kind: Deployment
metadata:
  # creationTimestamp: null
  # labels:
  #   app: mysql8
  name: mysql8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
  template: # plantilla del pod
    metadata:
      creationTimestamp: null
      labels:
        app: mysql8
    spec:
      containers:
        - image: mysql:8
          name: mysql8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: sasa
            - name: MYSQL_DATABASE
              value: msvc_usuarios
          volumeMounts:
            - name: data-mysql
              mountPath: /var/lib/mysql
          # resources: {}
      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: mysql-pvc
#        - name: data-mysql
#          hostPath:
#            path: /var/lib/mysql
#            type: DirectoryOrCreate
# status: {}