version: "3.9"

# Por defecto se crean todos los servicios en la misma red, entonces no hay necesidad de especificar
# explicitamente la red que comparten
services:

  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_PASSWORD=sasa
      - POSTGRES_DB=msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: curenosm/usuarios:latest
    # build:
    #   context: ./
    #   dockerfile: ./msvc-usuarios/Dockerfile
    # env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: sasa
      CURSOS_URL: msvc-cursos:8002
    ports:
      - "8001:8001"
    depends_on:
      - mysql8
    networks:
      - spring
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
    image: curenosm/cursos:latest
    # build:
    #   context: ./
    #   dockerfile: ./msvc-cursos/Dockerfile
    # env_file: ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
      USUARIOS_URL: msvc-usuarios:8001
    ports:
      - "8002:8002"
    depends_on:
      - postgres14
      - msvc-usuarios
    networks:
      - spring
    restart: always

networks:
  spring:
    name: spring

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres