apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  username: cm9vdA== # Base64 Encoding
  password: c2FzYQ== # Base64 Encoding

---

apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM= # Base64 Encoding
  password: c2FzYQ== # Base64 Encoding
