#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mysql://${DB_IP:10.20.30.40}:${DB_PORT:3306}/${DB_NAME:msvc-cursos}
#    username: ${DB_USERNAME:user}
#    password: ${DB_PASSWORD:Mipassword1+}